server:
  port: 8087
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: account
          uri: lb://accounts-service
          predicates:
            - Path=/accounts-service/**
        - id: content-fetch-service
          uri: lb://content-fetch-service
          predicates:
            - Path=/content-fetch-service/**
        - id: content-interaction-service
          uri: lb://content-interaction-service
          predicates:
              - Path=/content-interaction-service/**
        - id: movies-service
          uri: lb://movies-service
          predicates:
            - Path=/movies-service/**
        - id: shows-service
          uri: lb://shows-service
          predicates:
            - Path=/shows-service/**
        - id: signin-service
          uri: lb://signin-service
          predicates:
            - Path=/signin-service/**